GET localhost:3000/tickets/users/3
Authorization: Bearer {{token}}

> {%
client.test(
    "Request executed successfully",
    function() {
        client.assert(response.status === 200, "Response status is not 200");
    }
);
%}

###
GET localhost:3000/converters/1/logs

> {%
client.test(
    "Request executed successfully",
    function() {
        client.assert(response.status === 200, "Response status is not 200");
    }
);
%}
###
GET localhost:3000/tickets/1

> {%
client.test(
    "Request executed successfully",
    function() {
        client.assert(response.status === 200, "Response status is not 200");
    }
);
%}

###
POST localhost:3000/token
Content-Type: application/json
Accept: application/json

{
  "username": "Harry4324",
  "password": "companyadmin"
}

> {%
client.global.set("token", response.body.token);
%}


###
POST localhost:3000/customers
Content-Type: application/json
Accept: application/json

{
  "role" : "Client",
  "username": "Klaus",
  "password": "12345678",
  "first_name": "Klaus",
  "last_name": "Kazazi",
  "email": "lucaklaus921@gmail.com",
  "phone_number": "698317572"
}

> {%
client.test(
    "Request executed successfully",
    function() {
        client.assert(response.status === 200, "Response status is not 200");
    }
);
%}
###
POST localhost:3000/tickets/manualadd
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "log_id" : "2124651357192351"
}

> {%
client.test(
    "Request executed successfully",
    function() {
        client.assert(response.status === 200, "Response status is not 200");
    }
);
%}